version: "3.8"
services:
  lastbot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FB_PAGE_ACCESS_TOKEN=${FB_PAGE_ACCESS_TOKEN}
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./:/app
    restart: unless-stopped
